### ISSUE TITLE
Is dice number really random

### ISSUE THREAD

**Issue by mjhpour** [mort3za/ludo#14]
I play for 5 minutes and i don't get 6. I think the random function can be better to provide equal chance for all players. The computer have dice to 6 in 6 or 7 try but i don't get 6.

**Comment by mort3za** [comment]
Random function in the project is a popular npm package. https://www.npmjs.com/package/mersenne-twister
Do you have a better solution?

**Comment by mjhpour** [comment]
No i don't have.
